### PR TITLE
deferred: add zipseq and zipseq'

### PR DESCRIPTION
**Pull request by pyr**
Hi!

In a number of cases I find myself having to wait on a collection of deferreds. While it's fine to
`apply zip'`, I find this to improve legibility of the resulting code.

Am I missing an obvious way to do this?

### CODE REVIEW

**Comment by pyr** [comment]
(the build failure seems unrelated and triggers on master as well)

**Comment by pyr** [comment]
If #172 goes in I will rebase on top of it to make the build pass

**Comment by pyr** [comment]
It now builds thanks to #172, happy to have more thoughts on whether this is a good idea or not

**Comment by lurodrigo** [comment]
I think that's a great idea, I also need to `(apply d/zip' deferreds)` often.

**Comment by pyr** [comment]
any interest in this one?

**Comment by KingMob** [comment]
@pyr Thanks again for your hard work, but I really think the new functions are just too similar. While I agree `zipseq`'s param behavior may be the better default choice compared to when Manifold was first written, I'm not sure the improvement is enough to justify having two sets of almost-identical fns in the namespace.

**Pull request closed without merging**
